spring:
  datasource:
    url: jdbc:${DATABASE}://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: ${DIALECT}
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: ${DIALECT}
  profiles:
    active: dev
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    filter: true
    tagsSorter: alpha
server:
  port: 8090

access_expiration: ${access_token}
refresh_expiration: ${refresh_token}

private_key: ${private}
public_key: ${public}
base_url: ${url}


Jwt_Secret_Key: ${SECRET_KEY}

MTN_UNIQUE_CODE: ${MTN}
GLO_UNIQUE_CODE: ${GLO}
AIRTEL_UNIQUE_CODE: ${AIRTEL}
ETISALAT_UNIQUE_CODE: ${ETISALAT}
