DB_HOST: localhost
DB_NAME: xpress
DB_USERNAME: postgres
DB_PASSWORD: saheedajayi
DB_PORT : 5432
DATABASE: postgresql
DIALECT : org.hibernate.dialect.PostgreSQLDialect

SECRET_KEY: "OIDCu9SZ9U5LGqF6mW12KLuSxO70GPfqw3W2fh4uciXEi17bxij7229eNsVXRZnpsOa7pMb8gGbfJdl8YmnZ5uuaA43RPRH1v8720TWYUwAST90hzdLdzVYh54WXm44"


private: vrp4uaLOW8PqrGm5uXg1GiQbyIQ0q7h7_CVASPRV
public: Bearer oZq98neVMWBNcrj580rz3O15IOLSYIgd_CVASPUB
url: https://billerstest.xpresspayments.com:9603/api/v1/airtime/fulfil


# 3 hours
access_token: 10800
# 1 week
refresh_token: 604800

MTN: "MTN_24207"
GLO: "GLO_30387"
AIRTEL: "AIRTEL_22689"
ETISALAT: "9MOBILE_69358"